### ISSUE TITLE
Support for custom PMD rules (JAR)

### ISSUE THREAD

**Issue by PrabakaranSK** [acanda/eclipse-pmd#22]
Hi,

Couldn't see any documentation about how to associate a Custom PMD Rules JAR in eclipse-pmd plugin.

The Custom JAR has the following layout:

    custompmd.jar:  
        ├─ META-INF
        │       └─ MANIFEST.MF
        ├─ com
            └─ pmd
                └─ custom
                       └─ AvoidHardcodingRule.class
(The `AvoidHardcodingRule` class extends `AbstractJavaRule`)

**Comment by acanda** [comment]
You can use your custom rule classes if you add your jar as an Eclipse plug-in fragment to your Eclipse installation. The host of the plug-in fragment must be `ch.acanda.eclipse.pmd.core`.

To convert the jar to a plug-in fragment you have to modify the file `MANIFEST.MF` file and add a few manifest headers. The following is a complete manifest of an Eclipse plug-in fragment: 

```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: Custom PMD Rules
Bundle-SymbolicName: org.example.customrules
Bundle-Version: 1.0.0
Fragment-Host: ch.acanda.eclipse.pmd.core;bundle-version="1.4.1"
Bundle-RequiredExecutionEnvironment: JavaSE-1.7
```
 You can choose your own values for the headers `Bundle-Name`, `Bundle-SymbolicName` and `Bundle-Version`. The value of the header `Bundle-ManifestVersion` must be `2`. `Fragment-Host` must contain the symbolic name of the host bundle `ch.acanda.eclipse.pmd.core` and optionally the version of eclipse-pmd you have installed. `Bundle-RequiredExecutionEnvironment` specifies the minimum execution environment the plug-in fragment requires. Its value is `JavaSE-1.7` if you compiled it with Java 7 or `JavaSE-1.8` if you used Java 8.

Once you changed the manifest of your jar you can copy it into the folder `dropins` of your eclipse installation. Your plug-in fragment is installed when you start Eclipse.

**Comment by PrabakaranSK** [comment]
@acanda - It worked.  Thanks a lot for prompt reply.
