### ISSUE TITLE
CRITICAL: Update Site link is not accessible: http://www.acanda.ch/eclipse-pmd/release/latest/

### ISSUE THREAD

**Issue by PrabakaranSK** [acanda/eclipse-pmd#26]
When dragged the "Install" button to Eclipse, Eclipse Marketplace shows error "No repository found at http://www.acanda.ch/eclipse-pmd/release/latest.".

Seems like the link is either down or having some permission issues.

**Comment by acanda** [comment]
I just tried dragging the "Install" button and it worked. My server logs show that the update site is and was up and running too. Do you need a proxy to access the internet? If so can you check if the proxy is  configured correctly in Eclipse?
Also note that you will get a "Permission denied" message when you try to access the update site with a browser as there is no website at that URL. You should however be able to download http://www.acanda.ch/eclipse-pmd/release/latest/artifacts.jar.
