### ISSUE TITLE
Zipped update site

### ISSUE THREAD

**Issue by Maze-fr** [acanda/eclipse-pmd#28]
Hello,

I work in a company where the firewall is not very permissive, so when I try to install or to update eclipse-pmd, I got error messages...
Could it be possible to have an update site zip so we could use it to install eclipse-pmd ?

**Comment by acanda** [comment]
I created a zipped update site for offline installation: https://github.com/acanda/eclipse-pmd/releases/tag/Release_1.6. Let me know if this works for you.

**Comment by Maze-fr** [comment]
It works wonderful.
Great thanks to you for doing it so quickly.
