### ISSUE TITLE
BUG: Rule.start() is not called before Rule.apply()

### ISSUE THREAD

**Issue by cheppsn** [acanda/eclipse-pmd#32]
I've written a couple of rules that perform some setup and statistics/teardown in their `start()` and `end()` methods, respectively.

When I wrote an Eclipse Fragment to integrate them with the Acanda PMD-Plugin, I noted that neiter `start()` nor `end()` is called before calling `Rule.apply()` (as [promised by the `Rule` interface](https://github.com/pmd/pmd/blob/39d77e849aac127cb9ccf428a0b4850c1f9b3502/pmd-core/src/main/java/net/sourceforge/pmd/Rule.java#L298)).

Please compare the code in Acanda [here](https://github.com/acanda/eclipse-pmd/blob/Release_1.7/ch.acanda.eclipse.pmd.core/src/ch/acanda/eclipse/pmd/builder/Analyzer.java#L79)  (calling `runPMD` of the Acanda Plugin's Analyzer) with the comparable code piece [here](https://github.com/pmd/pmd/blob/pmd/5.4.x/pmd-core/src/main/java/net/sourceforge/pmd/processor/MonoThreadProcessor.java#L53) (PMD's `MonoThreadProcessor` performing analysis).

The `MonoThreadProcessor` calls `rs.start(ctx)` and `rs.end(ctx)` when running an analysis. This should also be peformed by the Acanda plugin.

**Comment by acanda** [comment]
Thank you for finding that bug and taking the time to find out how it's done right. The fix for this issue will be in eclipse-pmd 1.8.

**Comment by cheppsn** [comment]
Already fixed! Thanks! Can I pull/build a SNAPSHOT version of the plugin from somewhere until you release?

**Comment by acanda** [comment]
You can use the update site http://www.acanda.ch/eclipse-pmd/preview/issue32. Compared to eclipse-pmd 1.7.0 this contains the fix for this issue and the latest version of PMD (5.4.1).

**Comment by cheppsn** [comment]
Great, works as expected now.
