### ISSUE TITLE
PMD should not analyze derived files

### ISSUE THREAD

**Issue by phcouton** [acanda/eclipse-pmd#35]
Often the code generated by tools if far from being clean code. Analyzing such code generates a lot of PMD warnings. In one of my projects, I have a directory of java files generated by a Corba compiler: those files are analyzed by PMD, which reports nearly 500 warnings.

Eclipse has, in the properties of a source directory, some attributes which should set by a developer to give some hints to code analyzers:
* Resource/derived, which indicates that the directory contains generated code;
* Java compiler/ignore optional compile, which tells to the compiler that no warning should be emitted for the classes in this directory.

Could it be possible to use these attributes to tell to PMD to not analyze the generated classes ?

**Comment by acanda** [comment]
The plug-in already ignores files with the "derived" flag (it'd be a bug if it does not). If your code generator does not set the "derived" flag then it's also possible to [exclude those files in your rule set configuration](https://pmd.github.io/pmd-5.4.1/customizing/howtomakearuleset.html#Excluding_files_from_a_ruleset).

**Comment by phcouton** [comment]
As you can see on the capture below, there is strange behavior of Eclipse:
* The source directory `pub/generated-sources/idl` contains generated code with warnings. Since it is tagged `derived`, no warnings are shown on it;
* however, the directories hierarchy is show in the Eclipse explorer, but with the warning icon on the parent directories (`pub` and `pub/generated-sources`), which are not used as source directories. Strange.
* In addition, the "Problems" view of Eclipse reports the nearly 500 warnings generated by PMD.


![pmd-capture](https://cloud.githubusercontent.com/assets/13865666/11713664/147ca1f8-9f35-11e5-9f41-52eb6c6babfe.png)

**Comment by acanda** [comment]
The plug-in only ignores files that are themselves marked as derived. It is not sufficient if they just have a derived ancestor directory.
I could change this so the plug-in also ignores files that are not marked as derived themselves but have a derived ancestor directory.
