### ISSUE TITLE
An error occurred while automatically activating bundle ch.acanda.eclipse.pmd.core

### ISSUE THREAD

**Issue by acanda** [acanda/eclipse-pmd#36]
Submitted by @rsandidfc in another issue:

I've just installed PMD for the first time, and on launching Eclipse am immediately presented with:

Errors occurred during the build.
Error instantiating builder 'ch.acanda.eclipse.pmd.builder.PMDBuilder'.
Plug-in ch.acanda.eclipse.pmd.core was unable to load class ch.acanda.eclipse.pmd.builder.PMDBuilder.
An error occurred while automatically activating bundle ch.acanda.eclipse.pmd.core (1671).
Plug-in ch.acanda.eclipse.pmd.core was unable to load class ch.acanda.eclipse.pmd.builder.PMDBuilder.
An error occurred while automatically activating bundle ch.acanda.eclipse.pmd.core (1671).

I'm running Mars on Win2k8
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600
eclipse-pmd-1.8.0-201512061933
PMD for Eclipse 4.0.8.v20151204-2156

**Comment by acanda** [comment]
I noticed you installed two different PMD plugins: eclipse-pmd and PMD for Eclipse.
PMD for Eclipse uses an older version of PMD which seems to cause trouble with eclipse-pmd.
If you uninstall PMD for Eclipse then this problem should go away.

You can uninstall PMD for Eclipse select "Help > About Eclipse" (Windows) or "Eclipse > About Eclipse" (Mac), then click the button "Installation Details". In the tab "Installed Software" search for the plugin "PMD Plugin" with Id "net.sourceforge.pmd.eclipse.feature.group", select it and click on the button "Uninstall...".

Please let me know if this solved your problem.

**Comment by rsandidfc** [comment]
Hi - yes de-installing the PMD for Eclipse removes that exception - I removed both PMD for Eclipse and eclipse-pmd, then I re-added eclipse-pmd. Now I'm in a state where if I try to enable any project in the workspace with PMD, I'm unable to add any rulesets. I've tried every workspace, project, filesystem, nothing works. The dialog always says that the ruleset at whichever location is invalid and I can never click finish. There are no pmd.xml files or .eclipse-pmd files anywhere on the filesystem.

**Comment by acanda** [comment]
You have to create a rule set (pmd.xml) yourself. The PMD website has a page explaining [how to make a new rule set](https://pmd.github.io/pmd-5.4.1/customizing/howtomakearuleset.html). The eclipse-pmd website has step by step instructions of [how to set up PMD in Eclipse](https://acanda.github.io/eclipse-pmd/getting-started.html) once you have created the rule set.
