### ISSUE TITLE
Eclipse Neon (4.6) install through marked but nothing shows up

### ISSUE THREAD

**Issue by akarnokd** [acanda/eclipse-pmd#37]
I've installed the plugin through the Eclipse Market but neither the preferences, nor any context menu shows any PMD-related points. The error log doesn't reference anything related to this. Should the plugin work for 4.6?

**Comment by acanda** [comment]
The plug-in works with Eclipse Neon. You can [set up PMD in the project properties](http://acanda.github.io/eclipse-pmd/getting-started.html). Let me know if you find the PMD property page there.

**Comment by mefly2012** [comment]
thanks! It resolve my problem.
