### ISSUE TITLE
Remote ruleset: rules caching/refresh frequency?

### ISSUE THREAD

**Issue by srinivas-os** [acanda/eclipse-pmd#40]
In case of remote ruleset, does this plugin cache the downloaded PMD rules locally?

If so, for what duration, and what is the cache refresh frequency?

Or is it a one-time download of the rules? (I don't think this is the case as per docs)

**Comment by acanda** [comment]
Remote rulesets are cached locally and are refreshed every hour.
Note that a remote ruleset cannot be used to work off-line (for more than an hour) as the cached ruleset is not persistent and expires after an hour.

**Comment by srinivas-os** [comment]
Thanks for the clarification, closing this.
