### ISSUE TITLE
The rule set configuration at the given location is invalid

### ISSUE THREAD

**Issue by zhuker** [acanda/eclipse-pmd#42]
even on default ruleset
```
<?xml version="1.0"?>
<ruleset name="Custom ruleset"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 http://pmd.sourceforge.net/ruleset_2_0_0.xsd">
  <description>
  This ruleset checks my code for bad stuff
  </description>
</ruleset>
```
i get `The rule set configuration at the given location is invalid` message when trying to add the ruleset
![screen shot 2017-01-03 at 7 35 30 pm](https://cloud.githubusercontent.com/assets/4367682/21616827/cee91a78-d1eb-11e6-898d-fb0c0d749ac3.jpg)

**Comment by acanda** [comment]
This error message shows up when your ruleset file is not proper xml, doesn't validate against the PMD ruleset schema or contains invalid rule names (usually typos).

If you validate the ruleset you provided against the ruleset schema you will get the following error:
```
Error - Line 9, 11: org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 11; cvc-complex-type.2.4.b: The content of element 'ruleset' is not complete. 
One of '{"http://pmd.sourceforge.net/ruleset/2.0.0":exclude-pattern, "http://pmd.sourceforge.net/ruleset/2.0.0":include-pattern, "http://pmd.sourceforge.net/ruleset/2.0.0":rule}' is expected.
```
This means that you need to add at least one `rule` tag. I recommend that you open and edit the ruleset file with Eclipse's XML editor so you can see validation errors like this.

I know the error message is not very helpful and there is already issue #39 which addresses this problem.

**Comment by zhuker** [comment]
should any of these work?
http://pmd.sourceforge.net/pmd-4.3.0/howtomakearuleset.html

**Comment by zhuker** [comment]
maybe these
http://pmd.sourceforge.net/pmd-5.1.1/howtomakearuleset.html

**Comment by zhuker** [comment]
I validated the ruleset but it still doesn't get imported by the plugin
do you have an example ruleset that works for you?
![screen shot 2017-01-05 at 6 57 55 pm](https://cloud.githubusercontent.com/assets/4367682/21689463/0edfc314-d379-11e6-9cc1-f001f0c17052.jpg)

![screen shot 2017-01-05 at 6 58 48 pm](https://cloud.githubusercontent.com/assets/4367682/21689462/0ed26e94-d379-11e6-9399-a8986169eb71.jpg)

**Comment by acanda** [comment]
The rulesets from PMD 4.x do not work while those from PMD 5.x should work.

PMD changed the naming of the rules a bit from version 4.x to 5.x. What used to be e.g. `rulesets/imports.xml/DuplicateImports` is now `rulesets/java/imports.xml/DuplicateImports` (note the `java`). They also renamed or even removed a few rules.

**Comment by zhuker** [comment]
tried both 5x and 4x - no luck
do you have an example ruleset that works for you?

**Comment by acanda** [comment]
The rulesets I use for eclipse-pmd itself work for me. See pmd-*.xml in https://github.com/acanda/eclipse-pmd/blob/master/ch.acanda.eclipse.pmd/ e.g. https://github.com/acanda/eclipse-pmd/blob/master/ch.acanda.eclipse.pmd/pmd-base.xml.

**Comment by zhuker** [comment]
Thanks! it got imported!
This error messages most likely means java8 syntax support is not setup somewhere right?
![screen shot 2017-01-05 at 7 09 05 pm](https://cloud.githubusercontent.com/assets/4367682/21689855/8cf7af86-d37a-11e6-83fe-13bd90945675.jpg)

**Comment by acanda** [comment]
This is PMD telling you that it cannot parse the File TimePickerTest.java and therefore will not find any PMD issues. This usually happens when the file contains code that does not compile.

You don't have to turn on Java 8 support in PMD somewhere as it always uses a Java 8 parser to analyse the code.

Does the code in TimePickerTest.java compile? If not then this log entry will disappear when you fix it. If it does compile then you might have found a bug in PMD's parser.
