### ISSUE TITLE
Suppress "Unsupported @SuppressWarnings("PMD")" warning

### ISSUE THREAD

**Issue by acanda** [acanda/eclipse-pmd#5]
The Eclipse Java compiler creates warnings for unsupported `@SuppressWarnings` token. It would be nice if the eclipse-pmd plugin could suppress these warnings for the `PMD` and `PMD.xyz` token.

**Comment by slaout** [comment]
This has the disadvantage that Eclipse does not report any unsupported token at all!

There is a bug report on Eclipse project: feel free to support this issue: bugs.eclipse.org/bugs/show_bug.cgi?id=392045

**Comment by acanda** [comment]
There's also a much older issue on the Eclipse project for the same thing: https://bugs.eclipse.org/bugs/show_bug.cgi?id=122475
Feel free to support this issue as well.
