### ISSUE TITLE
Release 1.9

### ISSUE THREAD

**Issue by acanda** [acanda/eclipse-pmd#52]
The 1.9 release of eclipse-pmd is long overdue. If you want to help test the new version (@lukedirtwalker, @sratz), here is what you can do.

Install eclipse-pmd from the update site http://www.acanda.ch/eclipse-pmd/beta/1.9 (Help > Install New Software... > paste the URL into "Work with" > select everything from eclipse-pmd > Finish).

Now all you have to do is use the plugin for a week to see if you run into any problems. If eclipse-pmd runs into an unexpected problem it will show a message box with a short error message. Also keep an eye on the view "Error Log". This is where you can see eclipse-pmd logging errors, warnings and info messages.

Open an new issue if you find something that is not working. Add a comment to this issue if you didn't encounter any problems after a week.

Thank you very much for your help!

**Comment by neelu-sarkar** [comment]
Hi @acanda 

I'm goint to install and help out with the testing too.

Would be great to get the new version released for our project!

Neelu

**Comment by lukedirtwalker** [comment]
Thanks,

Installed it today. Seems to work so far.

Cheers,
Lukas

**Comment by acanda** [comment]
Thank you all for helping!

**Comment by neelu-sarkar** [comment]
We've got a reasonable amount of custom rules and exclusions and no problems so far either.

**Comment by acanda** [comment]
Just as I wanted to do the release I noticed that a new version of PMD has been release. So I updated the beta version of eclipse-pmd 1.9. If you want to help testing the new beta then you just have to let Eclipse check for new updates and it will be installed (assuming you have already used the update site for this beta).

**Comment by acanda** [comment]
Did anyone update and use the beta with the new version of PMD?

**Comment by lukedirtwalker** [comment]
Yes, I Updated as soon as you said to. No problems as with the previous
version.

Thanks,
Lukas

**Comment by neelu-sarkar** [comment]
Yeah - I've been using it and no problems so far.

**Comment by acanda** [comment]
I just released eclipse-pmd 1.9. Thanks for all your help!
