### ISSUE TITLE
eclipse-pmd 1.14 depends on pmd 6.6.0 and asm 6.1.1, but pmd 6.6.0 depends on asm 6.2

### ISSUE THREAD

**Issue by xlmkjd** [acanda/eclipse-pmd#56]
eclipse-pmd 1.4 0 Depend on pmd 6.6.0 and asm.6.1.1 ，but pmd6.6 Depend on asm 6.2.   
it will bring some problems

**Comment by acanda** [comment]
Thank you for reporting this bug. This will be fixed in the next version (where I also update to PMD 6.8.0 and asm 6.2.1).
