### ISSUE TITLE
Problem installing on STS 4

### ISSUE THREAD

**Issue by antoniovivalda** [acanda/eclipse-pmd#58]
Good Morning, 

I've installed PMD on Spring STS4, but when I enable PMD on a Project I get this error:

Errors occurred during the build.
Error instantiating builder 'net.sourceforge.pmd.eclipse.pmdBuilder'.
Plug-in "net.sourceforge.pmd.eclipse" was unable to instantiate class "net.sourceforge.pmd.eclipse.builder.PMDBuilder".
net/sourceforge/pmd/TargetJDKVersion
Plug-in "net.sourceforge.pmd.eclipse" was unable to instantiate class "net.sourceforge.pmd.eclipse.builder.PMDBuilder".
net/sourceforge/pmd/TargetJDKVersion

This is my Java version:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

And STS version:
Spring Tool Suite 4 

Version: 4.0.0.RELEASE
Build Id: 201809220817

Thank you 

Antonio

**Comment by adangel** [comment]
"net.sourceforge.pmd.eclipse.builder.PMDBuilder" is from the plugin here: https://github.com/pmd/pmd-eclipse-plugin
I don't know, what "net/sourceforge/pmd/TargetJDKVersion" is.... is this a custom class?

Are you using eclipse-pmd (this project) or [pmd-eclipse-plugin](https://github.com/pmd/pmd-eclipse-plugin)?

Please specify the exact versions of the PMD plugin, you have installed.

Thanks,
Andreas

**Comment by antoniovivalda** [comment]
Hi Andreas,

I've removed the pmd-eclipse-plugin and reistalled eclipse-pmd and everything works fine

Thank you

Antonio
