### ISSUE TITLE
Bug: After importing an exising project, no more PMD checks were performed

### ISSUE THREAD

**Issue by bohni** [acanda/eclipse-pmd#65]
I imported a Maven project in Eclipse (Import > Maven > Exisiting Maven Projects) and enabled the PMD plugin. Then I choosed a ruleset in project folder (src/main/config/pmd/ruleset.xml). -> All works fine.

I added plugin-config-file (#7) `.eclipse-pmd` to source control (Git).

My team members cloned the repository and imported the Maven project in Eclipse.

PMd checks are not performed, although PMD is enabled in project properties and the ruleset is listed and activated.

If we remove the ruleset (Apply and Close) and re-add it (Apply and Close), the checks are performed and violations are displayed again.

**Comment by acanda** [comment]
Do you also add `.project` to git? Because without this file the project will not have the nature `ch.acanda.eclipse.pmd.builder.PMDNature` and without this nature the PMD plugin will not be activated for that project.

**Comment by bohni** [comment]
No, I haven't added `.project`. Didn't think of PMDNature. Thanks.
