### ISSUE TITLE
Bug: ruleset of other projects are also listed

### ISSUE THREAD

**Issue by bohni** [acanda/eclipse-pmd#66]
On project properties there are listed all ruelsets, also some where defined as "project" on other projects.
Those were marked with a warning sign and "file not found" tool tip.

**Comment by acanda** [comment]
This works as intended. When you have a different pmd ruleset for each project then you most likely have it at the same location with the same filename in each project (e.g. all projects have a `pmd.xml` in a `config` folder). With this feature it makes it easier to set up all those projects. You dont have to go throught the wizard for each project but can simply do it for one project and then pick the same configuration for all other projects.

**Comment by bohni** [comment]
Thanks for clarifying.
