### ISSUE TITLE
Use Rulesets with unkonwn rules (from newer PMD versions)

### ISSUE THREAD

**Issue by bohni** [acanda/eclipse-pmd#68]
I want to use a rule set that contains rules from a newer version of PMD.

Since the plugin lists the rules individually, it should ignore an unknown rule when importing and not just display the "<file> is not a valid PMD rule set configuration" hint and make it impossible to select the rule set file.

The skipped rules could be listed after the import.

**Comment by acanda** [comment]
I'm using PMD itself to load the rules from the ruleset file. I either get the rules if the file was valid or an exception if it was not. Unfortunately the exception can be anything from an NullPointerException to some xml parser exceptions and none of them have a usable message that will be helpful when show in the UI. I (or someone else) would have to reimplement the rule loading to give a better hint than "this is not a valid PMD rule set configuration". So until PMD provides better error messages or we find another way to give better hints there is unfortunately not much I can do.

I have however just released a new version with the latest version of PMD so you can use your ruleset file.

**Comment by bohni** [comment]
Thanks for the reason and new version(s).
